import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from "@/theme";
import { Box, CssBaseline } from "@mui/material";
import Sidebar from "../component/Sidebar";
import MobileBottomNav from "../component/MobileBottomNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppRouterCacheProvider>
      <ThemeProvider theme={theme} >
        <Box sx={{ display: "flex", minHeight: '100vh' }}>
          <CssBaseline/>
          <Sidebar/>
          <Box component='main' sx={{ paddingBottom: 10, width: '100%'}}>
            {children}
          </Box>
          <MobileBottomNav/>
        </Box>
      </ThemeProvider>
    </AppRouterCacheProvider>
  );
}
