import { UserProvider } from "@auth0/nextjs-auth0/client"
import { Box, CssBaseline} from "@mui/material";
import { ThemeProvider } from "@mui/material/styles";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { Inter } from "next/font/google";
import theme from "@/theme";
import DetailSidebar from "../../component/DetailSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <DetailSidebar/>
      <Box component='main' sx={{ flexGrow: 1, p: 3}} >
        {children}
      </Box>
    </>

  )
}
