import { Box } from "@mui/material";
import { Inter } from "next/font/google";
import DetailSidebar from "../../component/DetailSidebar";
import DetailMobileBottomNav from "@/app/component/DetailMobileBottomNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <DetailSidebar/>
      <Box component='main' sx={{ flexGrow: 1, p: 3}} >
        {children}
      </Box>
      <DetailMobileBottomNav/>
    </>

  )
}
