import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Auth0Provider } from "@auth0/nextjs-auth0/client";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from "@/theme";
import { Box, CssBaseline } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <Auth0Provider>
        <body className={inter.className}>
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme} >
              <CssBaseline/>
              {children}
            </ThemeProvider>
          </AppRouterCacheProvider>
        </body>
      </Auth0Provider>
    </html>
  );
}
